services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - nginx-logs:/var/log/nginx
      - ./mock/nginx.conf:/etc/nginx/nginx.conf:ro

  mysql:
    image: mysql
    container_name: mysql
    volumes:
      - mysql-logs:/var/log/mysql
      - ./mock:/etc/mysql/conf.d/mysqld.cnf:ro
    environment:
      MYSQL_ROOT_PASSWORD: password

volumes:
  nginx-logs:
  mysql-logs:
