# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev
version: "3"

# vars:

tasks:
  ####################
  #      Deploy      #
  ####################
  deploy:
    desc: 本番環境のデプロイ
    deps:
      - checkout
    dir: webapp
    cmds:
      - bash restart_container.sh

  local:
    desc: ローカル環境のデプロイ
    dir: webapp
    cmds:
      - bash restart_container.sh

  test:
    desc: テストを実行
    dir: webapp/e2e
    cmds:
      - bash run_e2e_test.sh

  bench:
    desc: ベンチマークを実行 (restore なし)
    dir: benchmarker
    vars:
      # hostname が app- 始まりなら 9000, そうでなければ 9001
      PPROTEIN_PORT:
        sh: if [[ "$(hostname)" =~ ^app- ]]; then echo 9000; else echo 9001; fi
    cmds:
      - curl "localhost:{{.PPROTEIN_PORT}}/api/group/collect"
      - bash run_k6_and_score.sh

  grade:
    desc: デプロイ & 採点
    deps:
      - deploy
    cmds:
      - bash run.sh

  restore:
    desc: データベースのリストア & マイグレーション
    dir: webapp
    cmds:
      - bash restore_and_migration.sh

  ####################
  #     Utility      #
  ####################
  checkout:
    desc: リモートブランチに強制的にチェックアウト
    vars:
      BRANCH: '{{.CLI_ARGS | default "main"}}'
    cmds:
      - git fetch --all
      - git reset --hard origin/{{.BRANCH}}
      - git switch -C {{.BRANCH}} origin/{{.BRANCH}}

  ####################
  #     Internal     #
  ####################
