# yaml-language-server: $schema=https://taskfile.dev/schema.json
# https://taskfile.dev
version: "3"

# vars:

tasks:
  ####################
  #      Deploy      #
  ####################
  deploy:
    desc: 本番環境のデプロイ
    deps:
      - checkout
    cmds:
      - bash webapp/restart_container.sh

  local:
    desc: ローカル環境のデプロイ
    cmds:
      - bash webapp/restart_container.sh

  test:
    desc: テストを実行
    dir: webapp/e2e
    cmds:
      - bash run_e2e_test.sh

  bench:
    desc: ベンチマークを実行
    dir: benchmarker
    cmds:
      - bash run_k6_and_score.sh

  grade:
    desc: 採点を実行
    deps:
      - checkout
    cmds:
      - bash run.sh

  restore:
    desc: データベースのリストア & マイグレーション
    cmds:
      - bash webapp/restore_and_migration.sh

  ####################
  #     Utility      #
  ####################
  checkout:
    desc: リモートブランチに強制的にチェックアウト
    vars:
      BRANCH: '{{.CLI_ARGS | default "main"}}'
    cmds:
      - git fetch --all
      - git reset --hard origin/{{.BRANCH}}
      - git switch -C {{.BRANCH}} origin/{{.BRANCH}}

  ####################
  #     Internal     #
  ####################
