services:
  pprotein:
    container_name: pprotein
    restart: unless-stopped
    build:
      context: pprotein
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./pprotein/data:/opt/pprotein/data
      - nginx-logs:/var/log/nginx
      - mysql-logs:/var/log/mysql

volumes:
  nginx-logs:
    external: true
  mysql-logs:
    external: true
